spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_food_delivery
    username: postgres
    password: bunyod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123
springdoc:
  swagger-ui:
    path: sw

bot:
  name: "@first_first_1bot"
  token: "5047054234:AAH0uUFlFoNPRZBZg3OW6pKwPD34o-i18No"
