#bot:
#  name: "PDP Food Delivery Bot"
#  token: "@pdpfood_bot"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_food_delivery
    username: postgres
    password: iPhone0303
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123

bot:
  name: "pdpfood_bot"
  token: "5126126608:AAFl_X1rXzm0-H7mKz_-vcUXRHu-BYVQCmQ"


springdoc:
  swagger-ui:
    path: sw

