spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pdp_food_delivery
    username: postgres
    password: 19801980
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  messages:
    always-use-message-format: true
  security:
    user:
      name: admin
      password: admin123

springdoc:
  swagger-ui:
    path: sw
bot:
  name: "food_service"
  token: "5283213329:AAHTpDtGV8Q1SOndVvQvizP_HdlrbMfHpb8"


