#bot:
#  name: "PDP Food Delivery Bot"
#  token: "@pdpfood_bot"

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_delivery
    username: postgres
    password: iPhone0303
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    always-use-message-format: true
